# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-11 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StarWars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.URLField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'starwars',
            },
        ),
    ]
